Fix typo

diff --git a/codegen/cue-terraform-gen.bash.in b/codegen/cue-terraform-gen.bash.in
--- a/codegen/cue-terraform-gen.bash.in
+++ b/codegen/cue-terraform-gen.bash.in
@@ -42,7 +42,7 @@ if [ -z "$TERRAFORM_PROVIDER_SCHEMA" ]; then
 fi
 
 if [ -z "${BUILD_WORKSPACE_DIRECTORY-}" ]; then
-    echo "error: BUILD_WORKSPACE_DIRECOTRY not set" >&2
+    echo "error: BUILD_WORKSPACE_DIRECTORY not set" >&2
     exit 1
 fi
 pushd "${BUILD_WORKSPACE_DIRECTORY}" > /dev/null
